name: Approvals 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
    - name: checkout 
      uses: actions/checkout@v2

    - name: create the folder 
      run: mkdir workflows-1

  copy:
    runs-on: [ self-hosted ]
    needs: [ build ]
    
    steps:
    - name: create file
      run: echo "This file store the basic data" index.txt
