name: Approval Workflow Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  # Trigger this workflow when a PR targets the 'main' branch.

jobs:
  # Job 1: Build and Test
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Node.js (for example, you can adapt this to your project)
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        
      - name: Install Dependencies
        run: npm install
        
      - name: Run Tests
        run: npm test

  # Job 2: Manual Approval
  approval:
    runs-on: ubuntu-latest
    needs: build_and_test  # This job depends on the previous job completing successfully.

    steps:
      - name: Wait for Approval
        run: echo "Waiting for approval to proceed with deployment..."

    environment:
      name: production  # The environment name can be changed based on your use case.
      url: https://example.com  # Optional: Add a URL or related information for the environment.

    # Define the required approval for the environment before continuing
    approvals:
      required: 1  # At least 1 approval is required before continuing.

  # Job 3: Deploy (This job runs after approval)
  deploy:
    runs-on: ubuntu-latest
    needs: approval  # This job only runs if the approval job was successful.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: echo "Deploying application to production..."
        # Add your actual deployment steps here.

